openapi: '3.0.1'
info:
  title: ChatOnline
  description: Aplicação de Chat Online.
    Esse serviço implementa um Chat Online. No Chat Online, os usuários podem ler e escrever mensagens. 
    O usuário possui um perfil que ele pode editar os atributos como desejar. 
    Existe também o usuário administrador que pode fazer todo que um usuário comum faz, 
    com adição de banir um usuário e ver a lista de usuários.

  version: '1.1'
servers:
  - url: http://{host}:{porta}/api
    variables:
      host:
        default: localhost
      porta:
        default: '8000'

paths:
  /chat:
    get:
      operationId: getMessage
      summary: Retorna o chat.
      responses:
        '200':
          description: 'Sucesso'
          content: 
            application/json:
              schema:
                type: array
                minItems: 0
                items:
                  $ref: '#/components/schemas/mensagem'
    
    post:
      summary: Mandar uma mensagem.
      operationId: postMessage
      security:
        - bearer: []
        - oauth2: []
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario:
                  $ref: '#/components/schemas/mensagem/properties/usuario'
                mensagem:
                  $ref: '#/components/schemas/mensagem/properties/mensagem'
      responses:
        '201':
          description: Mensagem enviada.
          links:
            getPublicacaoById:
              description: O URI da mensagem enviada.
              operationId: getMessage
              parameters:
                id: $response.header.location

  

    

   





  /usuarios:
    get:
      summary: Retorna a lista de usuários cadastrados.
      responses:
        '200':
          description: 'OK'
          content: 
            application/json:
              schema:
                type: array
                minItems: 0
                items:
                  $ref: '#/components/schemas/usuario'

    post:
      summary: Cria um usuário.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/usuario"
      responses:
        "201":
          description: Criado.
        "400":
          description: Faltou algum parâmetro.

  /usuarios/{nome}:
    parameters:
      - nome:
        $ref: "#/components/parameters/nome"

    get:
      summary: Retorna os dados de um usuário.
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/usuario'
        '404':
          description: Não encontrado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/msg"
    
    put:
      summary: Cria ou altera os dados de um usuário.
      responses:
        '200':
          description: Alterou.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/msg"
        '201':
          description: Criou.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/msg"

    delete:
      summary: Apaga um usuário.
      responses:
        '200':
          description: 'OK'
        '404':
          description: Não encontrado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/msg"



components:
  schemas:  
    mensagem:
      type: object
      description: Uma mensagem.
      properties:
        id:
          type: string
          description: Um identificador gerado pelo sistema.
          example: '05d05m05az'
        usuario:
          type: "string"
          description: o dono da mensagem.
          example: Vanessa
        mensagem:
          type: string
          maxLength: 350
          example: Sou tão linda
        criacao:
          type: string
          format: date-time


    usuario:
      type: object
      properties:
        nome:
          type: string
          description: Nome usado como identificador.
          example: alicex
        nome_perfil: 
          type: string
          description: Nome legível, exibido, por exemplo, no perfil.
          example: Alice Xavier

    msg:
      type: object
      properties:
        tipo:
          type: string
          enum: [info, erro]
        conteudo:
          type: string


  responses:
    200:
      description: Ok.

    201:
      description: Recurso criado.

    400:
      description: Requisição inválida.
    
    404:
      description: Recurso não encontrado.


  parameters:
    idPublicacao:
      in: path
      name: idPublicacao
      required: true
      schema:
        $ref: '#components/publicacao/properties/id'
  
    nome:
      in: path
      name: nome
      required: true
      schema:
        $ref: '#components/usuario/properties/nome'
  

  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT

    oauth2:
      type: oauth2
      flows: 
        implicit:
          authorizationUrl: https://suap.ifrn.edu.br/api/v2/o/authorize/
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets